# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0egiiAzcU4pP7-6hBuwrQr2iIFr57SQ
"""

pip install nltk scikit-learn numpy

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

nltk.download('wordnet')

nltk.download('stopwords')

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.chat.util import Chat, reflections
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
import numpy as np
import json
import re
import random
import string

class TextPreprocessing:
  def __init__(self):
    self.lemmatizer = WordNetLemmatizer()
    self.stop_words = set(stopwords.words('english'))

  def remove_punctuation(self, text):
    return text.translate(str.maketrans('', '', string.punctuation))

  def tokenize(self, text):
    return word_tokenize(text)

  def lemmatize(self, tokens):
    return [self.lemmatizer.lemmatize(token) for token in tokens]

  def remove_stopwords(self, tokens):
    return [token for token in tokens if token.lower() not in self.stop_words]

  def preprocess(self, text):
    text = self.remove_punctuation(text)
    tokens = self.tokenize(text)
    tokens = self.lemmatize(tokens)
    #tokens = self.remove_stopwords(tokens)
    return ' '.join(tokens)

class AIPoweredChatbot:
    def __init__(self):
        self.vectorizer = CountVectorizer()
        self.model = MultinomialNB()
        self.pipeline = make_pipeline(self.vectorizer, self.model)
        self.train_data()

    def train_data(self):
        training_sentences = [
            "hello", "hi", "hey", "goodbye", "bye", "how are you", "I am fine", "thanks", "thank you",
            "what is your name", "who created you", "tell me a joke", "I love you"
        ]
        responses = [
            "Hi there!", "Hi there!", "Hello!", "Goodbye!", "Bye!", "I'm doing great, thanks!", "That's good to hear!",
            "You're welcome!", "You're welcome!",
            "I'm a chatbot!", "I was created by a developer!",
            "Why don't scientists trust atoms? Because they make up everything!", "I love you too!"
        ]

        self.pipeline.fit(training_sentences, responses)

    def chatbot_response(self, user_input):
        return self.pipeline.predict([user_input])[0]


#Basic rule based chatbot
def chatbot_response(user_input):
  user_input = user_input.lower()
  if "hello" in user_input or "hi" in user_input:
    return "Hello, how can I help you?"
  elif "how are you" in user_input:
    return "I'm just a chatbot, but I'm here to assist you!"
  elif "bye" in user_input or "goodbye" in user_input:
    return "Goodbye! Have a great day!"
  elif "your name" in user_input:
    return "I'm a chatbot, What can I do for you?"
  else:
    return "I'm sorry, I didn't understand that."

pairs = [
    [
        r"hello|hi|hey",
        ["Hello, How can I help you","Hey there! What's up?","Hi! how's it going"]
    ],
    [
        r"what is your name",
        ["I'm a chatbot, What can I do for you?"]
    ],
    [
        r"how are you",
        ["I'm just a chatbot, but I'm doing great"]
    ],
    [
        r"(.*) your name",
        ["My name is Chatbot. What's yours?","I am Chatbot, your virtual assistant"]
    ],
    [
        r"(.*) help (.*)",
        ["I can help with you general queries.How can I assist you?","Sure, Let me know how I can help you?"]
    ],
    [
        r"bye|goodbye",
        ["Goodbye! Have a great day!","Bye! Take care"]
    ],
    [
        r"(.*)",
        ["I'm sorry, I didn't understand that.","Could you please rephrase that?"]
    ]
]

chatbot  = Chat(pairs,reflections)

print("AI Powered Chatbot") # Changed from "Basic rule based chatbot"
preprocessor = TextPreprocessing()
ai_bot = AIPoweredChatbot()
print("\n")
print("Chatbot: How can I help you?")
while True:
  user_input = input("User: ")
  preprocessed_text = preprocessor.preprocess(user_input)
  if user_input.lower() == "exit":
    print("Chatbot: Goodbye! Have a great day!")
    break
  else:
    #response = chatbot_response(preprocessed_text) #basic rule based chatbot
    #response = chatbot.respond(preprocessed_text) #nltk based chatbot using nltk
    response = ai_bot.chatbot_response(preprocessed_text) #AI Powered chatbot
    print("Chatbot: ",response)


# print("Data preprocessing example")
# text = "Hello, How are you doing today? I am reading a book."
# preprocessor = TextPreprocessing()
# print("Original Text: ",text)
# print("Preprocesses Text: ",preprocessor.preprocess(text))

print("Data preprocessing example")
text = "Hello, How are you doing today? I am reading a book."
preprocessor = TextPreprocessing()
print("Original Text: ",text)
print("Preprocesses Text: ",preprocessor.preprocess(text))

print("\nIntermediary steps")
example_text = "Hello, How are you doing today? I am reading a book."
print("Remove Punctuation: ",example_text)
example_tokens = preprocessor.tokenize(example_text)
print("Tokenize: ",example_tokens)
print("Lemmatize: ",preprocessor.lemmatize(example_tokens))
print("Remove Stopwords: ",preprocessor.remove_stopwords(preprocessor.lemmatize(example_tokens)))

